#Compose file format  version
version: '3.1'

services:
  mongo:
    image: mongo:4.4
    volumes:
      - ./data/db:/data/db
      - ./temp:/temp
    restart: "no"
    ports:
      - ${MONGO_PORT}:27017
    healthcheck:
      test: "exit 0"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - ${MONGO_EXPR_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL          : mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/
